#!/usr/bin/env python3
"""Generate docs/commands/options.md: every stage's options from its argparse
wiring and SCHEMA, so the reference never lags the code. Run after changing a
stage's arguments; tests/unit/test_docs_options.py fails when it is stale.

    python3 tools/gen_options_doc.py            # write
    python3 tools/gen_options_doc.py --check    # exit 1 if docs/commands/options.md differs
"""

from __future__ import annotations

import argparse
import importlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from agentic_chimes import cli  # noqa: E402

GENERIC = [
    ("--output-dir", "Where the stage writes; remembers inputs (idempotent), `--force` to redo."),
    ("--json-in", "Read inputs from a JSON file (keys = option names with underscores); JSON wins over flags."),
    ("--json-out", "Write the result JSON here instead of stdout."),
    ("--describe", "Print the stage's schema and exit."),
    ("--force", "Re-run even if this output directory holds a finished run."),
    ("--dry-run", "Submitting stages only: render the job script without submitting."),
]


def _fmt_default(v):
    if v is None or v is argparse.SUPPRESS:
        return ""
    if isinstance(v, (list, dict)):
        return "`" + json.dumps(v) + "`"
    return f"`{v}`"


def _type_name(prop):
    t = prop.get("type")
    if isinstance(t, list):
        t = "/".join(x for x in t if x != "null")
    if prop.get("enum"):
        return "one of " + ", ".join(f"`{e}`" for e in prop["enum"])
    return t or ""


def render() -> str:
    out = ["# All options", "",
           "*Generated by `tools/gen_options_doc.py` from each stage's argument parser and schema; "
           "`chimes-agent <stage> --describe` prints the same schema. Every stage also accepts:*", ""]
    out += ["| option | meaning |", "|---|---|"] + [f"| `{f}` | {d} |" for f, d in GENERIC] + [""]
    for mod_name in cli.STAGE_MODULE_NAMES:
        mod = importlib.import_module(f"agentic_chimes.stages.{mod_name}")
        parser = argparse.ArgumentParser(prog=mod.NAME, add_help=False)
        mod.add_arguments(parser)
        props = (getattr(mod, "SCHEMA", {}) or {}).get("properties", {})
        required = set((getattr(mod, "SCHEMA", {}) or {}).get("required", []))
        out += [f"## `{mod.NAME}`", "", getattr(mod, "SUMMARY", ""), "",
                f"Reference: [{mod.NAME}]({mod.NAME}.md).", "",
                "| option | type | default | description |", "|---|---|---|---|"]
        rows = []
        for a in parser._actions:
            longs = [o for o in a.option_strings if o.startswith("--")]
            if not longs:
                continue
            prop = props.get(a.dest, {})
            default = a.default if a.default not in (None, argparse.SUPPRESS) else prop.get("default")
            if isinstance(a, (argparse._StoreTrueAction, argparse._StoreFalseAction)):
                typ = "flag"
            else:
                typ = _type_name(prop) or (getattr(a.type, "__name__", "") if a.type else "string")
            desc = prop.get("description", "") or (a.help or "")
            if a.dest in required:
                desc = "**required.** " + desc
            rows.append(f"| `{'`, `'.join(longs)}` | {typ} | {_fmt_default(default)} | {desc} |")
        out += rows + [""]
    return "\n".join(out).rstrip() + "\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args(argv)
    target = ROOT / "docs" / "commands" / "options.md"
    text = render()
    if args.check:
        if not target.is_file() or target.read_text() != text:
            print(f"{target} is stale: run python3 tools/gen_options_doc.py", file=sys.stderr)
            return 1
        return 0
    target.write_text(text)
    print(target)
    return 0


if __name__ == "__main__":
    sys.exit(main())
